# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PFBGUI.ui'
#
# Created: Thu Feb 28 10:35:27 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.input_canvas.setGeometry(QtCore.QRect(10, 10, 791, 371))
        self.input_canvas.setObjectName("input_canvas")
        self.output_canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.output_canvas.setGeometry(QtCore.QRect(10, 400, 791, 371))
        self.output_canvas.setObjectName("output_canvas")
        self.inp_abs_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.inp_abs_radbut.setGeometry(QtCore.QRect(820, 50, 122, 24))
        self.inp_abs_radbut.setObjectName("inp_abs_radbut")
        self.inp_imag_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.inp_imag_radbut.setGeometry(QtCore.QRect(820, 110, 122, 24))
        self.inp_imag_radbut.setObjectName("inp_imag_radbut")
        self.inp_real_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.inp_real_radbut.setGeometry(QtCore.QRect(820, 80, 122, 24))
        self.inp_real_radbut.setObjectName("inp_real_radbut")
        self.out_imag_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.out_imag_radbut.setGeometry(QtCore.QRect(820, 500, 122, 24))
        self.out_imag_radbut.setObjectName("out_imag_radbut")
        self.out_real_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.out_real_radbut.setGeometry(QtCore.QRect(820, 470, 122, 24))
        self.out_real_radbut.setObjectName("out_real_radbut")
        self.out_abs_radbut = QtWidgets.QRadioButton(self.centralwidget)
        self.out_abs_radbut.setGeometry(QtCore.QRect(820, 440, 122, 24))
        self.out_abs_radbut.setObjectName("out_abs_radbut")
        self.input_label = QtWidgets.QLabel(self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(330, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setUnderline(True)
        font.setBold(False)
        self.input_label.setFont(font)
        self.input_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_label.setObjectName("input_label")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(330, 400, 111, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setUnderline(True)
        font.setBold(False)
        self.output_label.setFont(font)
        self.output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_label.setObjectName("output_label")
        self.viewlabel1 = QtWidgets.QLabel(self.centralwidget)
        self.viewlabel1.setGeometry(QtCore.QRect(830, 10, 71, 18))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.viewlabel1.setFont(font)
        self.viewlabel1.setObjectName("viewlabel1")
        self.viewlabel2 = QtWidgets.QLabel(self.centralwidget)
        self.viewlabel2.setGeometry(QtCore.QRect(830, 400, 71, 18))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.viewlabel2.setFont(font)
        self.viewlabel2.setObjectName("viewlabel2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(800, 10, 20, 761))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(820, 30, 101, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(820, 420, 101, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(820, 530, 101, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(820, 140, 101, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 23))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuNew_2 = QtWidgets.QMenu(self.menuNew)
        self.menuNew_2.setObjectName("menuNew_2")
        self.menuPfb = QtWidgets.QMenu(self.menuNew_2)
        self.menuPfb.setObjectName("menuPfb")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionEdit_parameters = QtWidgets.QAction(MainWindow)
        self.actionEdit_parameters.setObjectName("actionEdit_parameters")
        self.actionEdit_processing = QtWidgets.QAction(MainWindow)
        self.actionEdit_processing.setObjectName("actionEdit_processing")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setObjectName("actionOutput")
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionMeerKAT_1K = QtWidgets.QAction(MainWindow)
        self.actionMeerKAT_1K.setObjectName("actionMeerKAT_1K")
        self.actionMeerKAT_4K = QtWidgets.QAction(MainWindow)
        self.actionMeerKAT_4K.setObjectName("actionMeerKAT_4K")
        self.actionCorrelator = QtWidgets.QAction(MainWindow)
        self.actionCorrelator.setObjectName("actionCorrelator")
        self.menuPfb.addAction(self.actionCustom)
        self.menuPfb.addAction(self.actionMeerKAT_1K)
        self.menuPfb.addAction(self.actionMeerKAT_4K)
        self.menuNew_2.addAction(self.menuPfb.menuAction())
        self.menuNew_2.addAction(self.actionCorrelator)
        self.menuNew.addAction(self.menuNew_2.menuAction())
        self.menuNew.addAction(self.actionSave)
        self.menuConfig.addAction(self.actionEdit_parameters)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionOutput)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionParameters)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.inp_abs_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Absolute", None, -1))
        self.inp_imag_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Imaginary", None, -1))
        self.inp_real_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Real", None, -1))
        self.out_imag_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Imaginary", None, -1))
        self.out_real_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Real", None, -1))
        self.out_abs_radbut.setText(QtWidgets.QApplication.translate("MainWindow", "Absolute", None, -1))
        self.input_label.setText(QtWidgets.QApplication.translate("MainWindow", "Input", None, -1))
        self.output_label.setText(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.viewlabel1.setText(QtWidgets.QApplication.translate("MainWindow", "View:", None, -1))
        self.viewlabel2.setText(QtWidgets.QApplication.translate("MainWindow", "View:", None, -1))
        self.menuNew.setTitle(QtWidgets.QApplication.translate("MainWindow", "file", None, -1))
        self.menuNew_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "new", None, -1))
        self.menuPfb.setTitle(QtWidgets.QApplication.translate("MainWindow", "pfb", None, -1))
        self.menuConfig.setTitle(QtWidgets.QApplication.translate("MainWindow", "config", None, -1))
        self.menuRun.setTitle(QtWidgets.QApplication.translate("MainWindow", "run", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "save", None, -1))
        self.actionEdit_parameters.setText(QtWidgets.QApplication.translate("MainWindow", "input", None, -1))
        self.actionEdit_processing.setText(QtWidgets.QApplication.translate("MainWindow", "edit processing", None, -1))
        self.actionInput.setText(QtWidgets.QApplication.translate("MainWindow", "input", None, -1))
        self.actionOutput.setText(QtWidgets.QApplication.translate("MainWindow", "output", None, -1))
        self.actionParameters.setText(QtWidgets.QApplication.translate("MainWindow", "parameters", None, -1))
        self.actionCustom.setText(QtWidgets.QApplication.translate("MainWindow", "custom*", None, -1))
        self.actionMeerKAT_1K.setText(QtWidgets.QApplication.translate("MainWindow", "MeerKAT(1K)", None, -1))
        self.actionMeerKAT_4K.setText(QtWidgets.QApplication.translate("MainWindow", "MeerKAT(4K)", None, -1))
        self.actionCorrelator.setText(QtWidgets.QApplication.translate("MainWindow", "correlator", None, -1))

