#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 21:32:43 2019

@author: talon
"""
import numpy as np
from fixpoint import cfixpoint


testarray = np.arange(-2,2.1,0.1)
s = cfixpoint(10,5,method="ROUND_INFTY")
s.from_complex(testarray)
s[2].method

